defmodule Datem.Reporting do
  @moduledoc """
  Aggregations, dashboards, and CSV exports over the logs the other contexts
  write.

  Reporting is deliberately read-only: it never issues identifiers or records
  scans, it only aggregates `access_logs`, `scan_logs` and tickets that
  `Datem.Access`, `Datem.Scanning` and `Datem.Ticketing` already own. Every
  query goes through `Datem.Tenancy`, so a report can only ever describe the
  caller's own organisation.

  Exports are requested here and generated by `Datem.Reporting.ExportWorker`
  on the `:exports` Oban queue, so a large CSV never blocks a LiveView.
  """

  import Ecto.Query, warn: false

  alias Datem.Access
  alias Datem.Access.{AccessLog, Vehicle, VisitorPass}
  alias Datem.Accounts.Scope
  alias Datem.Repo
  alias Datem.Reporting.{Export, ExportWorker}
  alias Datem.Scanning
  alias Datem.Scanning.ScanLog
  alias Datem.Tenancy
  alias Datem.Ticketing
  alias Datem.Ticketing.{Event, Ticket}

  @recent_denials_limit 10

  ## Org home dashboard

  @doc """
  The organisation's home dashboard: who is on-site today, which events are
  running, and what has recently been turned away.

  `now` is injectable so callers (and tests) can reason about "today"
  deterministically; it is interpreted in UTC, the same clock every log is
  written with.
  """
  def dashboard(%Scope{} = scope, now \\ nil) do
    now = now || DateTime.utc_now()
    onsite = Access.list_onsite(scope)

    %{
      onsite: onsite,
      onsite_count: length(onsite),
      visitors_today: visitors_today(scope, now),
      active_events: active_events(scope, now),
      recent_denials: recent_denials(scope),
      alerts: Access.list_alerts(scope)
    }
  end

  @doc "Distinct subjects scanned `in` since midnight UTC."
  def visitors_today(%Scope{} = scope, now \\ nil) do
    now = now || DateTime.utc_now()

    AccessLog
    |> Tenancy.scope(scope)
    |> where([l], l.direction == "in" and l.scanned_at >= ^start_of_day(now))
    |> select([l], count(fragment("distinct (?, ?)", l.subject_type, l.subject_id)))
    |> Repo.one()
  end

  @doc """
  Events currently running (started, not yet ended) with their registered and
  checked-in counts. An event with no end time is treated as running until it
  is closed.
  """
  def active_events(%Scope{} = scope, now \\ nil) do
    now = now || DateTime.utc_now()

    events =
      Event
      |> Tenancy.scope(scope)
      |> where([e], e.status != "closed")
      |> where([e], is_nil(e.starts_at) or e.starts_at <= ^now)
      |> where([e], is_nil(e.ends_at) or e.ends_at >= ^now)
      |> order_by([e], asc: e.starts_at)
      |> Repo.all()

    counts = ticket_counts(scope, Enum.map(events, & &1.id))

    Enum.map(events, fn event ->
      %{registered: registered, checked_in: checked_in} =
        Map.get(counts, event.id, %{registered: 0, checked_in: 0})

      %{event: event, registered: registered, checked_in: checked_in}
    end)
  end

  @doc "The most recent non-accepted scans across every checkpoint."
  def recent_denials(%Scope{} = scope, limit \\ @recent_denials_limit) do
    ScanLog
    |> Tenancy.scope(scope)
    |> where([l], l.result != "accepted")
    |> order_by([l], desc: l.scanned_at, desc: l.id)
    |> limit(^limit)
    |> preload(:scan_type)
    |> Repo.all()
  end

  defp ticket_counts(_scope, []), do: %{}

  defp ticket_counts(scope, event_ids) do
    Ticket
    |> Tenancy.scope(scope)
    |> where([t], t.event_id in ^event_ids and t.status != "cancelled")
    |> group_by([t], t.event_id)
    |> select(
      [t],
      {t.event_id,
       %{
         registered: count(t.id),
         checked_in: filter(count(t.id), t.status == "checked_in")
       }}
    )
    |> Repo.all()
    |> Map.new()
  end

  ## Access reports

  @doc """
  Entries and exits over a time range, broken down by site, by access point,
  and by day.

  `filters` is a plain map (string or atom keys) of `from`, `to`, `site_id`
  and `access_point_id`; see `parse_filters/1` for how each is interpreted.
  Dates are inclusive: a `to` of `2026-09-03` covers all of that day.
  """
  def access_report(%Scope{} = scope, filters \\ %{}) do
    filters = parse_filters(filters)
    query = access_logs_query(scope, filters)

    %{
      filters: filters,
      totals: access_totals(query),
      by_site: access_by_site(query),
      by_access_point: access_by_access_point(query),
      by_day: access_by_day(query)
    }
  end

  defp access_totals(query) do
    query
    |> select([l], %{
      entries: filter(count(l.id), l.direction == "in"),
      exits: filter(count(l.id), l.direction == "out"),
      unique_subjects: count(fragment("distinct (?, ?)", l.subject_type, l.subject_id))
    })
    |> Repo.one()
  end

  defp access_by_site(query) do
    query
    |> group_by([site: s], [s.id, s.name])
    |> order_by([site: s], asc: s.name)
    |> select([l, site: s], %{
      site_id: s.id,
      name: s.name,
      entries: filter(count(l.id), l.direction == "in"),
      exits: filter(count(l.id), l.direction == "out")
    })
    |> Repo.all()
  end

  defp access_by_access_point(query) do
    query
    |> group_by([access_point: ap, site: s], [ap.id, ap.name, s.name])
    |> order_by([access_point: ap], asc: ap.name)
    |> select([l, access_point: ap, site: s], %{
      access_point_id: ap.id,
      name: ap.name,
      site_name: s.name,
      entries: filter(count(l.id), l.direction == "in"),
      exits: filter(count(l.id), l.direction == "out")
    })
    |> Repo.all()
  end

  defp access_by_day(query) do
    query
    |> group_by([l], fragment("date_trunc('day', ?)", l.scanned_at))
    |> order_by([l], asc: fragment("date_trunc('day', ?)", l.scanned_at))
    |> select([l], %{
      day: fragment("date_trunc('day', ?)", l.scanned_at),
      entries: filter(count(l.id), l.direction == "in"),
      exits: filter(count(l.id), l.direction == "out")
    })
    |> Repo.all()
  end

  defp access_logs_query(scope, filters) do
    AccessLog
    |> Tenancy.scope(scope)
    |> join(:inner, [l], ap in assoc(l, :access_point), as: :access_point)
    |> join(:inner, [access_point: ap], s in assoc(ap, :site), as: :site)
    |> filter_from(filters.from)
    |> filter_to(filters.to)
    |> filter_site(filters.site_id)
    |> filter_access_point(filters.access_point_id)
  end

  defp filter_from(query, nil), do: query
  defp filter_from(query, from), do: where(query, [l], l.scanned_at >= ^from)

  defp filter_to(query, nil), do: query
  defp filter_to(query, to), do: where(query, [l], l.scanned_at <= ^to)

  defp filter_site(query, nil), do: query
  defp filter_site(query, site_id), do: where(query, [site: s], s.id == ^site_id)

  defp filter_access_point(query, nil), do: query

  defp filter_access_point(query, access_point_id),
    do: where(query, [access_point: ap], ap.id == ^access_point_id)

  ## Event reports

  @doc """
  Attendance for one event: registered vs checked-in (with the check-in rate
  as a percentage), the same split per ticket type, and the accepted-scan
  tally for every checkpoint configured on the event.
  """
  def event_report(%Scope{} = scope, %Event{} = event) do
    tickets = Ticketing.list_tickets(scope, event)
    live_tickets = Enum.reject(tickets, &(&1.status == "cancelled"))
    checked_in = Enum.count(live_tickets, &(&1.status == "checked_in"))

    %{
      event: event,
      registered: length(live_tickets),
      cancelled: length(tickets) - length(live_tickets),
      checked_in: checked_in,
      check_in_rate: percentage(checked_in, length(live_tickets)),
      by_ticket_type: by_ticket_type(live_tickets),
      scan_types: Scanning.tallies(scope, Scanning.list_scan_types_for(scope, event))
    }
  end

  defp by_ticket_type(tickets) do
    tickets
    |> Enum.group_by(& &1.ticket_type.name)
    |> Enum.map(fn {name, tickets} ->
      checked_in = Enum.count(tickets, &(&1.status == "checked_in"))

      %{
        name: name,
        registered: length(tickets),
        checked_in: checked_in,
        check_in_rate: percentage(checked_in, length(tickets))
      }
    end)
    |> Enum.sort_by(& &1.name)
  end

  @doc "Whole-percent share of `count` in `total`; 0 when there is nothing to divide."
  def percentage(_count, 0), do: 0
  def percentage(count, total), do: round(count * 100 / total)

  ## Exports

  @doc """
  Requests a CSV export and enqueues the job that builds it.

  Returns the `pending` `%Export{}` immediately; the LiveView subscribes to
  `topic/1` and swaps in a download link once the worker finishes.
  """
  def request_export(%Scope{} = scope, kind, filters \\ %{}) do
    attrs = %{
      "kind" => to_string(kind),
      "filters" => stringify(filters),
      "organization_id" => Tenancy.organization_id!(scope),
      "requested_by_id" => scope.user && scope.user.id
    }

    with {:ok, export} <- %Export{} |> Export.changeset(attrs) |> Repo.insert(),
         {:ok, _job} <- %{"export_id" => export.id} |> ExportWorker.new() |> Oban.insert() do
      {:ok, export}
    end
  end

  def list_exports(%Scope{} = scope, limit \\ 50) do
    Export
    |> Tenancy.scope(scope)
    |> order_by([e], desc: e.inserted_at, desc: e.id)
    |> limit(^limit)
    |> Repo.all()
  end

  def get_export_for_scope!(%Scope{} = scope, id) do
    Export |> Tenancy.scope(scope) |> Repo.get!(id)
  end

  @doc false
  def get_export(id), do: Repo.get(Export, id)

  @doc "Marks an export as finished (or failed) and broadcasts the change."
  def finish_export(%Export{} = export, status, attrs \\ %{}) do
    case export |> Export.status_changeset(status, attrs) |> Repo.update() do
      {:ok, export} ->
        broadcast_export(export)
        {:ok, export}

      error ->
        error
    end
  end

  @doc "The PubSub topic carrying export progress for an organisation."
  def topic(organization_id), do: "org:#{organization_id}:exports"

  def subscribe_to_exports(%Scope{} = scope) do
    Phoenix.PubSub.subscribe(Datem.PubSub, topic(Tenancy.organization_id!(scope)))
  end

  defp broadcast_export(%Export{} = export) do
    Phoenix.PubSub.broadcast(
      Datem.PubSub,
      topic(export.organization_id),
      {:export_updated, export}
    )
  end

  @doc """
  The directory completed exports are written to.

  Deliberately outside `priv/static`: an export is tenant data, so it is
  served by `DatemWeb.ExportController` after a scope check rather than by
  the static file plug.
  """
  def exports_dir do
    Application.get_env(:datem, :exports_dir) ||
      Path.join(:code.priv_dir(:datem), "exports")
  end

  @doc "Absolute path of a completed export's file."
  def export_path(%Export{filename: nil}), do: nil

  def export_path(%Export{organization_id: org_id, filename: filename}) do
    Path.join([exports_dir(), to_string(org_id), filename])
  end

  ## Export contents

  @doc """
  Builds `{headers, rows}` for an export. Called by the worker, but pure and
  scope-checked so it can be tested (and previewed) on its own.
  """
  def export_rows(%Scope{} = scope, "access_logs", filters) do
    filters = parse_filters(filters)

    logs =
      scope
      |> access_logs_query(filters)
      |> order_by([l], asc: l.scanned_at, asc: l.id)
      |> preload([:operator, access_point: :site])
      |> Repo.all()

    names = subject_names(scope, logs)

    rows =
      Enum.map(logs, fn log ->
        [
          log.scanned_at,
          log.direction,
          log.subject_type,
          Map.get(names, {log.subject_type, log.subject_id}, "Unknown"),
          log.access_point.site.name,
          log.access_point.name,
          log.operator && log.operator.email
        ]
      end)

    {~w(scanned_at direction subject_type subject site access_point operator), rows}
  end

  def export_rows(%Scope{} = scope, "attendees", filters) do
    filters = parse_filters(filters)
    event = Ticketing.get_event_for_scope!(scope, filters.event_id)

    rows =
      scope
      |> Ticketing.list_tickets(event)
      |> Repo.preload(:gs1_identifier)
      |> Enum.map(fn ticket ->
        [
          ticket.attendee_name,
          ticket.attendee_email,
          ticket.ticket_type.name,
          ticket.status,
          ticket.gs1_identifier && ticket.gs1_identifier.value,
          ticket.inserted_at
        ]
      end)

    {~w(attendee_name attendee_email ticket_type status gsrn registered_at), rows}
  end

  def export_rows(%Scope{} = scope, "scan_tallies", filters) do
    filters = parse_filters(filters)

    scan_types =
      case filters.event_id do
        nil ->
          Scanning.list_scan_types(scope)

        event_id ->
          Scanning.list_scan_types_for(scope, Ticketing.get_event_for_scope!(scope, event_id))
      end

    rows =
      scope
      |> Scanning.tallies(scan_types)
      |> Enum.map(fn tally ->
        [
          tally.scan_type.name,
          scan_type_scope_name(tally.scan_type),
          tally.claimed,
          tally.eligible
        ]
      end)

    {~w(scan_type scope claimed eligible), rows}
  end

  defp scan_type_scope_name(%{event: %{name: name}}), do: name
  defp scan_type_scope_name(%{site: %{name: name}}), do: name
  defp scan_type_scope_name(_scan_type), do: nil

  # Resolves the display name of every subject in one query per subject type,
  # rather than a lookup per log row.
  defp subject_names(scope, logs) do
    ids = fn type -> for %{subject_type: ^type, subject_id: id} <- logs, do: id end

    passes =
      VisitorPass
      |> Tenancy.scope(scope)
      |> where([p], p.id in ^ids.("visitor_pass"))
      |> join(:inner, [p], v in assoc(p, :visitor))
      |> select([p, v], {{"visitor_pass", p.id}, v.name})
      |> Repo.all()

    vehicles =
      Vehicle
      |> Tenancy.scope(scope)
      |> where([v], v.id in ^ids.("vehicle"))
      |> select([v], {{"vehicle", v.id}, v.plate})
      |> Repo.all()

    Map.new(passes ++ vehicles)
  end

  @doc "The human label used for an export kind in the UI and its filename."
  def export_label("access_logs"), do: "Access logs"
  def export_label("attendees"), do: "Attendee list"
  def export_label("scan_tallies"), do: "Scan tallies"

  ## Filters

  @doc """
  Normalises a filter map coming from a form or from `exports.filters`
  (JSONB, so string keys) into atoms with parsed values.

  `from`/`to` accept a `YYYY-MM-DD` date and widen to cover the whole day in
  UTC, so a range reads the way an operator picks it.
  """
  def parse_filters(filters) when is_map(filters) do
    %{
      from: filters |> fetch(:from) |> parse_date(:start),
      to: filters |> fetch(:to) |> parse_date(:end),
      site_id: filters |> fetch(:site_id) |> parse_id(),
      access_point_id: filters |> fetch(:access_point_id) |> parse_id(),
      event_id: filters |> fetch(:event_id) |> parse_id()
    }
  end

  defp fetch(filters, key) do
    case Map.fetch(filters, key) do
      {:ok, value} -> value
      :error -> Map.get(filters, to_string(key))
    end
  end

  defp parse_date(value, _edge) when value in [nil, ""], do: nil
  defp parse_date(%DateTime{} = value, _edge), do: value

  defp parse_date(value, edge) when is_binary(value) do
    case Date.from_iso8601(value) do
      {:ok, date} -> to_datetime(date, edge)
      {:error, _} -> nil
    end
  end

  defp to_datetime(date, :start), do: DateTime.new!(date, ~T[00:00:00], "Etc/UTC")
  defp to_datetime(date, :end), do: DateTime.new!(date, ~T[23:59:59], "Etc/UTC")

  defp parse_id(value) when value in [nil, ""], do: nil
  defp parse_id(value) when is_integer(value), do: value

  defp parse_id(value) when is_binary(value) do
    case Integer.parse(value) do
      {id, ""} -> id
      _ -> nil
    end
  end

  defp stringify(filters) do
    Map.new(filters, fn {key, value} -> {to_string(key), value} end)
  end

  defp start_of_day(%DateTime{} = now) do
    now |> DateTime.to_date() |> DateTime.new!(~T[00:00:00], "Etc/UTC")
  end
end
